### ISSUE TITLE
"Request is not supported. (0x80004005)" error while trying to limit memory commit on a process.

### ISSUE THREAD

**Issue by Midi-In** [lowleveldesign/process-governor#73] opened 2024-08-19 09:33 UTC
Procgov fails when trying to limit maximum memory for a process (Firefox 115.14.0esr (32-bit) in this case), with following error message:

```
$ procgov32.exe --maxmem 1200M --pid=1812
Process Governor v2.13.24103.12 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Maximum committed memory (MB):              1,200

ERROR: The request is not supported. (0x80004005)
```
![image](https://github.com/user-attachments/assets/a08088cc-3a35-47ff-b2fa-780b2d559f19)

Operating system the issue occurs on is Windows 8.1 x64

**Comment by lowleveldesign** [comment] 2024-08-20 08:20
Hey, thanks for reporting the problem. I tried reproducing it on Windows Server 2019 (I don't have any Windows 8.1 available), but can't. Does running as admin change anything? It could be also the limitation of this version of Windows. On Windows 7, when process had a job object assigned (and Firefox creates its own job objects), you could not assign another job to it. I'm not sure if this limitation was lifted for Windows 8.1 or later.

![image](https://github.com/user-attachments/assets/a85a11a7-79ee-45f2-a05e-35081a88b4b2)

**Comment by Midi-In** [comment] 2024-08-27 17:37
I have tried running it with elevated privileges, but the behaviour remains unchanged. And yes, i need to actually test this programs with processes that don't start as jobs (i haven't tried yet, because FF was my main use case for now). I have identified using Process Explorer, that indeed, all child processes Firefox creates are started as jobs, so that might be the culprit.

**Comment by Midi-In** [comment] 2024-08-31 10:47
I have tested both procgov32 and procgov64 with processes other than Firefox, and it seems to be working correctly, although on pressing Ctrl+C to detach and terminate procgov, it throws the following error:
`procgov32.exe --maxmem 1200M --pid=5720
Process Governor v2.13.24103.12 - sets limits on processes
Copyright (C) 2023 Sebastian Solnica (lowleveldesign.org)

Maximum committed memory (MB):              1,200

Press Ctrl-C to end execution without terminating the process.

ERROR: Cannot access a disposed object.
Object name: 'Microsoft.Win32.SafeHandles.SafeFileHandle'.`

Despite that, it seems to be exiting correctly and leaving the newly created job process intact, running as expected.

**Comment by lowleveldesign** [comment] 2024-09-01 04:34
Thank you for checking. I'm closing this issue since it looks that it's related to Win 8.1 restrictions regarding job objects.

As you noticed, the "disposed object error" (a stupid bug on my side) does not affect procgov functionality and it will be fixed in the coming release :) Thanks

**Closed by lowleveldesign** 2024-09-01 04:34 UTC
